/*
 * Warning :
 * 
 * 		This File is auto generated by Minecraft Forge Class Generator
 * 		
 * 		Do NOT EDIT between those comment in case the lost of modify!
 * 
 * 		Do NOT DELETE Any Comment or you do not want use the Generator to 
 * 		edit your MOD!
 * 
 * */


package /*!var.mod.package.mod*/modgen.mod/**/;


import net.minecraft.client.settings.GameSettings;
import net.minecraft.init.Blocks;
import net.minecraft.world.GameRules;
import cpw.mods.fml.common.FMLContainer;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.event.FMLConstructionEvent;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLLoadCompleteEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.event.FMLServerAboutToStartEvent;
import cpw.mods.fml.common.event.FMLServerStartedEvent;
import cpw.mods.fml.common.event.FMLServerStartingEvent;
import cpw.mods.fml.common.event.FMLServerStoppedEvent;
import cpw.mods.fml.common.registry.EntityRegistry;
import cpw.mods.fml.common.registry.GameData;
import cpw.mods.fml.common.registry.GameRegistry;
/*!gen.mod.package*//**/


@Mod(modid =/*!var.mod.class*/ExampleMod/**/.MODID, 
	version = /*!var.mod.class*/ExampleMod/**/.VERSION ,
	name = /*!var.mod.class*/ExampleMod/**/.NAME ,
	useMetadata = false,
	modLanguage = "java",
	acceptedMinecraftVersions = /*!var.mod.minecraftversion*/""/**/,
	acceptableRemoteVersions =/*!var.mod.remoteversion*/""/**/,
	acceptableSaveVersions = /*!var.mod.saveversion*/""/**/,
	canBeDeactivated = /*!var.mod.canbedeactived*/false/**/,
	dependencies = /*!var.mod.dependencies*/""/**/)
public class /*!var.mod.class*/ExampleMod/**/
{
    public static final String MODID = /*!var.mod.modid*/"examplemod"/**/;
    public static final String VERSION = /*!var.mod.version*/"1.0"/**/;
    public static final String NAME = "ExampleMod";
    
    /*&OnPreInit*/
    /**
     * The Forge pre-init event.
     * 
     * This event usually fired when after loaded the core mods.
     * Please initialize your mod here.(like reading the configure file)
     * 
     * Please register your blocks and items here.
     * 
     * @param event
     */
    @EventHandler
    public void OnFoegePreInit(FMLPreInitializationEvent event)
    {
    	/*! gen.mod.hook.OnPreInit*/
    	/**/
    	
    	//TODO: add your own code here
    }
    /*&*/
    
    /*&OnInit*/
    /**
     * The Forge initialize event.
     * 
     * This event usually fired after register blocks and items.
     * You can modify blocks and items registered here. 
     * 
     * @param event
     */
    @EventHandler
    public void OnFoegeInit(FMLInitializationEvent event)
    {    	
    	/*!gen.mod.hook.OnInit*/
    	/**/
    	
    	//TODO: add your own code here
    	
        System.out.println("DIRT BLOCK >> "+Blocks.dirt.getUnlocalizedName());
    }
    /*&*/
    
    /*&OnPostInit*/
    /**
     * The Forge Post Initialize Event
     * This Event Will be Fired at the Last stage of Initialize 
     *  
     * @param event
     */
    @EventHandler 
    public void OnForgePostInit(FMLPostInitializationEvent event)
    {
    	/*!gen.mod.hook.OnPostInit*/
    	/**/
    	
    	//TODO:Add your own code here
    }
    /*&*/
    
    /*&OnLoadFinish*/
    /**
     * The Forge Load Complete Event.
     * Actually , this event is really useless unless you want to 
     * make some mod for Minecraft GUI.
     * 
     * @param event
     */
    public void OnForgeLoadFinish(FMLLoadCompleteEvent event)
    {
    	/*!gen.mod.hook.OnLoadFinish*/
    	/**/
    	
    	//TODO:Add your own code here
    }
    /*&*/
    
    /*&OnServerAboutToStart*/
    /**
     * This event will be fired before server start.
     * Only the ServerSide will receive this event.
     * 
     * @param event
     */
    public void OnServerAboutToStart(FMLServerAboutToStartEvent event)
    {
    	/*!gen.mod.hook.OnServerAboutToStart*/
    	/**/
    	
    	//TODO:Add your own code here
    }
    /*&*/
    
    /*&OnServerStarted*/
    /**
     * This event will be fired when server started.
     * Only the ServerSide will receive the event.
     * 
     * @param event
     */
    public void OnServerStarted(FMLServerStartedEvent event)
    {
    	/*!gen.mod.hook.OnServerStarted*/
    	/**/
    	
    	//TODO:Add your own code here
    }
    /*&*/
    
    /*&OnServerStarting*/
    /**
     * This event will be fire while starting server.
     * Only the ServerSide will receive this event.
     * 
     * @param event
     */
    public void OnServerStarting(FMLServerStartingEvent event)
    {
    	/*!gen.mod.hook.OnServerStarting*/
    	/**/
    	
    	//TODO:Add your own code here
    }
    /*&*/
    
    /*& OnServerStopped*/
    /**
     * This event will be fired after the server stopped
     * Only the ServerSide will receive this event.
     * 
     * @param event
     */
    public void OnServerStopped(FMLServerStoppedEvent event)
    {
    	/*!gen.mod.hook.OnServerStopped*/
    	/**/
    	
    	//TODO:Add your own code here
    }
    /*&*/
}
